version: '3.7'
services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - '/client/node_modules'
      - '/server/node_modules'
      - './:/app'
